### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by eduardokraus** [dthies/moodle-mod_plenum#1]
The readme needs to be clear on how to obtain all credentials.

![Captura de Tela 2024-10-19 às 08 49 57](https://github.com/user-attachments/assets/454ef89a-bf71-4fd9-9724-cb648b9ee8bb)

**Comment by dthies** [comment]
I added and section to the database description and the README to describe the dependencies. There is a link in to the Deft response block to configure that. The configuration so the service is done there so it does not make sense to duplicate it here. 
Similarly, sites may use a hosting provider for Jitsi or already have an existing local install. Since using Jitsi is optional and depends how it is provided explaining how to get the credentials is beyond the scope of the README. It is the responsibility of the Jitsi admin to provide them.
